# Generated by Django 5.2.5 on 2025-09-01 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_userregister_delete_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='four_wheelers',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='model',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='reg_number',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='two_wheelers',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='year',
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('scooter', 'Scooter'), ('car', 'Car'), ('other', 'Other')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('reg_number', models.CharField(blank=True, max_length=20, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='garage.userregister')),
            ],
        ),
    ]
