# Generated by Django 5.2.5 on 2025-09-01 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_remove_userregister_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregister',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
