# Generated by Django 5.2.5 on 2025-09-03 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_alter_userregister_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('garage_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('location', models.URLField(blank=True, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('services', models.JSONField(blank=True, default=list)),
                ('vehicles', models.JSONField(blank=True, default=list)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='service_docs/')),
                ('garage_logo', models.ImageField(blank=True, null=True, upload_to='service_docs/')),
                ('about', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
